### PR TITLE
Improve/fix required/nonzero validators

### LINKED ISSUE #20: requiredValidator should check for empty strings
Currently the [`requiredValidator`](https://github.com/urso/ucfg/blob/master/validator.go#L252) checks for non-nil. I think it should check the type and verify strings are not empty, which to me means checking `strings.TrimSpace(in) != ""`.

### PR DESCRIPTION
**Pull request by urso**
Check slices, strings and regular expression being empty.

updates `required` to check:
- string being not ""   intending: require requires string to be present and not empty
- pointers being set intending: pointers to struct must be set
- length of slice > 0 intending: array must be present at least one entry is required.

update nonzero to check:
- string being not "" intending: if present it must not be empty
- length of slice > 0: if array/slice present it must not be empty.

Closes #20

### CODE REVIEW

File: validator.go [hunk 1]
```diff
@@ -87,7 +88,11 @@ func runValidators(val interface{}, validators []validatorTag) error {
 	return nil
 }
 
-func validateNonZero(v interface{}, _ string) error {
+// validateNonZero implements the `nonzeror` validation tag.
```
Comment (andrewkroh) [inline validator.go]: `nonzeror`? Is that last `r` intentional?

Comment (urso) [inline validator.go]: ups

**Comment by andrewkroh** [comment]
LGTM
